<a href="https://colab.research.google.com/github/Namithas98/makaan.com-websraping/blob/main/Makaan_websraping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
#import all packages

import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
from IPython.display import clear_output

In [17]:
base_url='https://www.makaan.com/hyderabad-residential-property/buy-property-in-hyderabad-city?page='


owner_info=[]
no_of_bhk=[]
price_info=[]
loca_info=[]
cons_status=[]
pr_sq_info=[]
area_info=[]


for i in range(1,51):
  time.sleep(3)
  url=base_url+str(i)+'&_=1624455000063'
  req=requests.get(url)
  soup=BeautifulSoup(req.text,'html')

#owner information
own_in=soup.findAll('span',attrs={'class':'seller-type'})
for j in own_in:
  owner_info.append(j.text)



#BHK information 
b_info=soup.findAll('div',attrs={'class':'title-line'}) #bhk
for k in b_info:
  no_of_bhk.append(k.strong.span.text)


#price information
p_in=soup.findAll('div',attrs={'data-type':'price-link'})  
for l in p_in:
  price_info.append(l.text)

#Locality Information
loca_in=soup.findAll('span',attrs={'itemprop':'addressLocality'})  
for h in loca_in:
  loca_info.append(h.text)


#Construction Status
con_sta=soup.findAll('td',attrs={'class':'val'}) 
for r in con_sta:
  cons_status.append(r.text) 


#price/sq information
pr_per_sq=soup.findAll('td',attrs={'class':'lbl rate'}) 
for z in pr_per_sq:
  pr_sq_info.append(z.text) 


#Area information
area_in=soup.findAll('td',attrs={'class':'size'}) 
for n in area_in:
  area_info.append(n.text)

In [15]:
data=pd.DataFrame({'owner_info':owner_info,'BHK_info':no_of_bhk,'price_info':price_info,'locality_info':loca_info,'con_sta':cons_status,'pri_in':pr_sq_info,'Area_inf':area_info})
data

   owner_info BHK_info price_info  ...             con_sta         pri_in Area_inf
0       OWNER       3        37 L  ...  Under Construction  3,557 / sq ft    1040
1       OWNER       3        44 L  ...  Under Construction  3,548 / sq ft    1240
2       OWNER       3        44 L  ...  Under Construction  3,548 / sq ft    1240
3       OWNER       2        36 L  ...  Under Construction  3,529 / sq ft    1020
4       OWNER       2        36 L  ...  Under Construction  3,529 / sq ft    1020
5       OWNER       2        36 L  ...  Under Construction  3,529 / sq ft    1020
6       OWNER       2        36 L  ...  Under Construction  3,529 / sq ft    1020
7       OWNER       2        36 L  ...  Under Construction  3,529 / sq ft    1020
8       OWNER       3        44 L  ...  Under Construction  3,548 / sq ft    1240
9       OWNER       3        44 L  ...  Under Construction  3,548 / sq ft    1240
10      OWNER       3        44 L  ...  Under Construction  3,548 / sq ft    1240
11      OWNER       3        44 L  ...  Under Construction  3,548 / sq ft    1240
12      OWNER       2        38 L  ...  Under Construction  3,584 / sq ft    1060
13      OWNER       2        38 L  ...  Under Construction  3,653 / sq ft    1040
14      OWNER       2        38 L  ...  Under Construction  3,584 / sq ft    1060
15      OWNER       2        38 L  ...  Under Construction  3,584 / sq ft    1060
16      OWNER       3        37 L  ...  Under Construction  3,557 / sq ft    1040
17      OWNER       2        38 L  ...  Under Construction  3,653 / sq ft    1040
18      OWNER       2        38 L  ...  Under Construction  3,653 / sq ft    1040
19      OWNER       2        38 L  ...  Under Construction  3,584 / sq ft    1060

[20 rows x 7 columns]

In [16]:
data.to_csv('Makaan.csv',index=False)